// This is free and unencumbered software released into the public domain.
//
// Anyone is free to copy, modify, publish, use, compile, sell, or
// distribute this software, either in source code form or as a compiled
// binary, for any purpose, commercial or non-commercial, and by any
// means.

// CSRs
#define csr_custom_irq_mask		0x7C0
#define csr_custom_irq_pend		0x7C1
#define csr_custom_trap			  0x7C2

#define MTIME_BASE_ADDR			0xfffffff0
